-- ============================================
-- Exercise 5 : Triggers
-- ============================================

-- ============================================
-- Scenario 1
-- Update Customer Last Modified Date
-- ============================================

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

-- ============================================
-- Scenario 2
-- Audit Log for Transactions
-- ============================================

-- Create AuditLog Table

CREATE TABLE AuditLog
(
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    AccountID NUMBER,
    Amount NUMBER,
    TransactionType VARCHAR2(20),
    AuditDate DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN

    INSERT INTO AuditLog
    (
        TransactionID,
        AccountID,
        Amount,
        TransactionType,
        AuditDate
    )
    VALUES
    (
        :NEW.TransactionID,
        :NEW.AccountID,
        :NEW.Amount,
        :NEW.TransactionType,
        SYSDATE
    );

END;
/

-- ============================================
-- Scenario 3
-- Check Deposit and Withdrawal Rules
-- ============================================

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT ON Transactions
FOR EACH ROW

DECLARE
    v_Balance NUMBER;
BEGIN

    SELECT Balance
    INTO v_Balance
    FROM Accounts
    WHERE AccountID = :NEW.AccountID;

    IF :NEW.TransactionType = 'Withdrawal' THEN

        IF :NEW.Amount > v_Balance THEN
            RAISE_APPLICATION_ERROR
            (
                -20001,
                'Withdrawal exceeds available balance.'
            );
        END IF;

    ELSIF :NEW.TransactionType = 'Deposit' THEN

        IF :NEW.Amount <= 0 THEN
            RAISE_APPLICATION_ERROR
            (
                -20002,
                'Deposit amount must be positive.'
            );
        END IF;

    END IF;

END;
/